CFLAGS = -Wall -Wshadow -O3 -g -march=native -std=c11
LDLIBS = -lm

all: test trainer

sigmoid: CFLAGS += -Dgenann_act=genann_act_sigmoid_cached
sigmoid: all

threshold: CFLAGS += -Dgenann_act=genann_act_threshold
threshold: all

linear: CFLAGS += -Dgenann_act=genann_act_linear
linear: all

test: test.o genann.o

check: test
	./$^

trainer: trainer.o genann.o

clean:
	$(RM) *.o
	$(RM) test trainer *.exe
	$(RM) persist.txt

.PHONY: sigmoid threshold linear clean
